version: '3.9'

services:

  postgres:
    container_name: db_typeorm_compose
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: typeor_user_compose
      POSTGRES_PASSWORD: 123457
      POSTGRES_DB: postgres_compose
    ports:
     - "5432:5432" 
  app:
    build: .
    ports:
      - "3000:4001"
    depends_on:
      - postgres   