version: '3.9'

services:

  db:
    container_name: db_typeorm_compose
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: typeorm_user_compose
      POSTGRES_PASSWORD: 123457
      POSTGRES_DB: postgres_compose
    ports:
     - "9002:5432" 
    volumes: 
      - db:/var/lib/postgresql/data 
  app:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db  
    environment:
      TYPEORM_HOST: db
      TYPEORM_PORT: 5432
      TYPEORM_USERNAME: typeorm_user_compose
      TYPEORM_PASSWORD: 123457
      TYPEORM_NAME: postgres_compose
volumes:
  db:
  app:    
     